### PR TITLE
Mimic Blender slider behavior

### PR DESCRIPTION
**Pull request by MathemanFlo**
Currently the slider's position is changed by clicking on the sliders number to change it directly. This behavior is unfortunate.
This PR fixes
https://github.com/armory3d/armorpaint/issues/1244
https://github.com/armory3d/armorpaint/issues/1222#issue-1087172113 item number 9.
https://github.com/armory3d/armorpaint/issues/1069 the slider issue mentioned here

### CODE REVIEW

**Comment by luboslenco** [comment]
Looks great! Just need to check on one issue, where box selection is created in node editor when dragging the slider.

**Comment by MathemanFlo** [comment]
Sorry, I really overlooked this issue. What about this change? I could not see any negative side effects but doesn't mean anything.
I think Zui could need some z-order handling to avoid these problems. Maybe a stack to check which element is on top to determine recursibely on the stack where a mouse click belongs to.

**Comment by MathemanFlo** [comment]
I realized context menus like the layer menu had also broken sliders as it closed immediately.

**Comment by MathemanFlo** [comment]
🙈 no it does not make any difference as far as I can see. Thank you for pointing that out. You obviously know Zui better than me 😀

**Comment by luboslenco** [comment]
Super cool!

**Pull request merged**
