### PR TITLE
added an "alwaysUpdate" parameter to handle

### PR DESCRIPTION
**Pull request by Jarrio**
Just a quality of life change, this way you can just set the toggle once and not need to repeat it manually. I'm not sure why it's picking up other changes. I only changed, at most, 5~6 lines of code.

I've set the default value to false.

### CODE REVIEW

**Comment by luboslenco** [comment]
Sorry I was not able to merge due to conflicts. But I added `ui.alwaysRedraw` flag in https://github.com/armory3d/zui/commit/96cecebea401083d5e5d7eb166a005461eddc4fd, hopefully that fixes the issue.

**Comment by Jarrio** [comment]
No worries, much appreciated 👍

**Comment by Jarrio** [comment]
Just to mention, the reason I wanted this was `ui.text(changing variable)` wasn't getting updated when the value changed. Maybe an alternative (less expensive way) would be to redraw `ui.text`?

**Comment by sh-dave** [comment]
I actually like the idea of having the flag on the specific handle, so you could adjust it more targeted. But i guess it would require to propagate it to the parent handles as well?

**Comment by luboslenco** [comment]
Right now the whole (visible) ui is redrawn on change, would need some more work for that. The next boost should come once I split calls to ColoredShaderPainter and TextShaderPainter.

**Pull request closed without merging**
