### PR TITLE
Support TextArea in Canvas

### PR DESCRIPTION
**Pull request by mundusnine**
When this gets merged we will start work on including textArea to armory2d

### CODE REVIEW

**Comment by luboslenco** [comment]
It looks like changing the order of `ElementType` entries would break the existing canvas files? (since the type is saved at https://github.com/armory3d/zui/blob/master/Sources/zui/Canvas.hx#L317)

**Comment by mundusnine** [comment]
> 
> 
> It looks like changing the order of `ElementType` entries would break the existing canvas files? (since the type is saved at https://github.com/armory3d/zui/blob/master/Sources/zui/Canvas.hx#L317)

Yeah I hadn't thought of that but you are correct. Would you prefer we not have a breaking change and make the TextArea ElementType after the CProgressBar ?

**Comment by mundusnine** [comment]
Made the change.

**Comment by luboslenco** [comment]
Thanks a lot!

**Pull request merged**
